[project]
name = "sponsor_match"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "pandas>=2.2",
    "numpy>=2.2",
    "scikit-learn>=1.6",
    "joblib>=1.5",
    "threadpoolctl>=3.6",
    "python-dotenv>=1.1",
    "mysql-connector-python>=9.3",
    "geopy>=2.4",
]

[tool.setuptools]
packages = ["sponsor_match"]
