[mysql]
user         = "sponsor_user"
password     = "Sports-2025?!"
host         = "localhost"
port         = "3306"
database     = "sponsor_registry"
# optional override URL
url_override = "mysql+mysqlconnector://sponsor_user:Sports-2025?!@localhost:3306/sponsor_registry"
